Update test zoo
- Remove 'version' from docker-compose.yml
- Add Asciidoctor version to informative output
- Fix Asciidoctor install on OpenSUSE Tumbleweed
- Add Ubuntu 24.04 to test zoo
- Drop Ubuntu 18.04 from test zoo
- Add Fedora 40 to test zoo
- Add Fedora 41 to test zoo
- Drop Fedora 37 from test zoo
- Drop Fedora 38 from test zoo

Closes #648

diff --git a/test/docker/fedora41 b/test/docker/fedora41
--- a/test/docker/fedora41
+++ b/test/docker/fedora41
@@ -1,4 +1,4 @@
-FROM fedora:38
+FROM fedora:41
 
 RUN dnf update -y
 RUN dnf install -y \
@@ -31,4 +31,4 @@ RUN make install
 WORKDIR /root/code/test/
 RUN make -j2
 
-CMD ["bash", "-c", "./run_all -v ; cat all.log | grep 'not ok' ; ./problems ; FAILED=$? ; echo timew $( timew --version ) ; python --version ; cmake --version ; gcc --version ; exit $FAILED"]
+CMD ["bash", "-c", "./run_all -v ; cat all.log | grep 'not ok' ; ./problems ; FAILED=$? ; echo timew $( timew --version ) ; python --version ; cmake --version ; gcc --version ; asciidoctor --version ; exit $FAILED"]
diff --git a/test/docker/opensusetumbleweed b/test/docker/opensusetumbleweed
--- a/test/docker/opensusetumbleweed
+++ b/test/docker/opensusetumbleweed
@@ -7,10 +7,9 @@ RUN zypper install -y \
            man \
            python3 \
            python3-python-dateutil \
-           ruby
+           ruby \
+           ruby3.4-rubygem-asciidoctor
 
-RUN gem install asciidoctor -v 2.0.17
-RUN update-alternatives --install /usr/bin/asciidoctor asciidoctor /usr/bin//asciidoctor.ruby3.3 10
 RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10
 ENV TZ=Europe/Berlin
 
@@ -33,4 +32,4 @@ RUN make install
 WORKDIR /root/code/test/
 RUN make -j2
 
-CMD ["bash", "-c", "./run_all -v ; cat all.log | grep 'not ok' ; ./problems ; FAILED=$? ; echo timew $( timew --version ) ; python --version ; cmake --version ; gcc --version ; exit $FAILED"]
+CMD ["bash", "-c", "./run_all -v ; cat all.log | grep 'not ok' ; ./problems ; FAILED=$? ; echo timew $( timew --version ) ; python --version ; cmake --version ; gcc --version ; asciidoctor --version ; exit $FAILED"]
